/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef PCMFLOW_VERSION_H
#define PCMFLOW_VERSION_H

#define PCMFLOW_VERSION_MAJOR 0
#define PCMFLOW_VERSION_MINOR 2
#define PCMFLOW_VERSION_PATCH 1
#define PCMFLOW_VERSION_STR "0.2.1"

#endif // PCMFLOW_VERSION_H
